apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zfdq457k6-java-quarkus
  janus-idp.io/tekton: zfdq457k6-java-quarkus
  backstage.io/kubernetes-id: zfdq457k6-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zfdq457k6-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
